ALTER TABLE users ADD COLUMN IF NOT EXISTS chat_folders_json TEXT;

ALTER TABLE user_chats ADD COLUMN IF NOT EXISTS is_pinned INTEGER DEFAULT 0;
ALTER TABLE user_chats ADD COLUMN IF NOT EXISTS is_muted INTEGER DEFAULT 0;
ALTER TABLE user_chats ADD COLUMN IF NOT EXISTS folder_name TEXT;
